spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sportbuddy
    username: arif
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080


jwt.secret : "your-super-secure-and-very-long-32-byte-secret-key-here!!"
jwt.expiration-ms : 3600000