spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/sportbuddy}
    username: ${DB_USERNAME:arif}
    password: ${DB_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

jwt:
  secret: "bXlTdXBlclNlY3JldEtleUZvckpXVFNpblByb2R1Y3Rpb24xMjM0NTY3ODkwIQ=="
  expiration-ms: ${JWT_EXPIRATION_MS:3600000}
  refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION_MS:604800000}
